### ISSUE TITLE
Inference Pre-trained Model

### ISSUE THREAD

**Issue by ferdyandannes** [lzccccc/SMOKE#14]
Hello, first thank you for sharing this amazing work and release the code, it really help me a lot.
But I have several question I want to ask for
1. In the pre-trained model that you have provide, I try to run you provided pre-trained model model_final.pth, but I have a strange result like this:

Cyclist 0 0 0.29319998621940613 1101.7052001953125 157.85940551757812 1171.0078125 199.82049560546875 1.5821000337600708 0.6988000273704529 2.05430006980896 20.817399978637695 0.7282000184059143 27.693300247192383 0.9377999901771545 0.2808000147342682
Pedestrian 0 0 -0.156700000166893 0.0 4.8867998123168945 32.05400085449219 47.18880081176758 1.6751999855041504 0.8062000274658203 1.1485999822616577 -27.59119987487793 -6.371799945831299 33.09489822387695 -0.8515999913215637 0.28049999475479126
Cyclist 0 0 0.40369999408721924 928.3699951171875 211.3343048095703 984.5086059570312 262.87060546875 1.868499994277954 0.5382999777793884 1.90339994430542 13.737299919128418 3.1115000247955322 27.609399795532227 0.8654000163078308 0.28029999136924744
Pedestrian 0 0 -0.15150000154972076 1194.6259765625 286.85760498046875 1224.0 332.6874084472656 1.631100058555603 0.6679999828338623 0.9711999893188477 24.250900268554688 5.956200122833252 28.213600158691406 0.5586000084877014 0.2802000045776367
Cyclist 0 0 1.6592999696731567 1142.3118896484375 55.76430130004883 1169.814453125 108.3541030883789 1.6448999643325806 0.6118000149726868 1.9859000444412231 20.006200790405273 -2.709199905395508 25.61370086669922 2.3224000930786133 0.2797999978065491
Cyclist 0 0 0.09459999948740005 1166.0030517578125 62.07600021362305 1224.0 112.0342025756836 1.7129000425338745 0.58160001039505 1.8250000476837158 23.007600784301758 -2.739799976348877 27.437599182128906 0.7924000024795532 0.27970001101493835
Pedestrian 0 0 -0.09070000052452087 1170.5811767578125 236.30099487304688 1204.6690673828125 286.3161926269531 1.7871999740600586 0.7777000069618225 0.9431999921798706 22.403799057006836 3.9769999980926514 27.162599563598633 0.5989999771118164 0.2784000039100647
Cyclist 0 0 -0.021299999207258224 492.5469970703125 0.0 539.0078125 40.38359832763672 1.700700044631958 0.6797000169754028 2.018399953842163 -3.909600019454956 -6.295499801635742 31.283700942993164 -0.14560000598430634 0.27799999713897705

The image is using KITTI dataset. Do you think that my output is correct or not? Because when I see in the dataset there are car, but it detected as no cars.
Thank you

**Comment by Vinohith** [comment]
By default when you run this command : 
`python tools/plain_train_net.py --eval-only --config-file "configs/smoke_gn_vector.yaml"`
the code uses the pretrained ImageNet weights. This is the reason the predictions might be correct as expected.

To use the downloaded model_final.pth weights you will have to change the path for **WEIGHT** in `configs/smoke_gn_vector.yaml` to the path where the downloaded model_final.pth is stored.

This should solve the issue.

**Comment by no-Seaweed** [comment]
> By default when you run this command :
> `python tools/plain_train_net.py --eval-only --config-file "configs/smoke_gn_vector.yaml"`
> the code uses the pretrained ImageNet weights. This is the reason the predictions might be correct as expected.
> 
> To use the downloaded model_final.pth weights you will have to change the path for **WEIGHT** in `configs/smoke_gn_vector.yaml` to the path where the downloaded model_final.pth is stored.
> 
> This should solve the issue.

I followed the step you said by switching "catalog://ImageNetPretrained/DLA34" to "path/to/model_final.pth", but I got following error.

```
[2020-12-30 22:44:01,081] smoke.data.datasets.kitti INFO: Initializing KITTI val set with 3769 files loaded
[2020-12-30 22:44:01,250] smoke.engine.inference INFO: Start evaluation on kitti_train dataset(3769 images).
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3769/3769 [02:28<00:00, 25.31it/s]
[2020-12-30 22:46:30,189] smoke.engine.inference INFO: Total run time: 0:02:28.938225 (0.039516642227132366 s / img per device, on 1 devices)
[2020-12-30 22:46:30,189] smoke.engine.inference INFO: Model inference time: 0:02:16.556438 (0.03623147730676778 s / img per device, on 1 devices)
[2020-12-30 22:46:30,189] smoke.data.datasets.evaluation.kitti.kitti_eval INFO: performing kitti detection evaluation: 
Traceback (most recent call last):
File "tools/plain_train_net.py", line 103, in <module>
args=(args,),
File "/home/robot1/Shukai/SMOKE/smoke/engine/launch.py", line 56, in launch
main_func(*args)
File "tools/plain_train_net.py", line 80, in main
return run_test(cfg, model)
File "/home/robot1/Shukai/SMOKE/smoke/engine/test_net.py", line 26, in run_test
output_folder=output_folder,
File "/home/robot1/Shukai/SMOKE/smoke/engine/inference.py", line 74, in inference
output_folder=output_folder, )
File "/home/robot1/Shukai/SMOKE/smoke/data/datasets/evaluation/__init__.py", line 26, in evaluate
return kitti_evaluation(**args)
File "/home/robot1/Shukai/SMOKE/smoke/data/datasets/evaluation/kitti/kitti_eval.py", line 28, in kitti_evaluation
logger=logger
File "/home/robot1/Shukai/SMOKE/smoke/data/datasets/evaluation/kitti/kitti_eval.py", line 37, in do_kitti_detection_evaluation
predict_folder = os.path.join(output_folder, 'data')  # only recognize data
File "/home/robot1/anaconda3/envs/SMOKE/lib/python3.7/posixpath.py", line 80, in join
a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by czy341181** [comment]
@Vinohith , Sorry to bother you.  I have changed weight path in smoke_gn_vector.yaml by pretrained model. But I still got 0.02AP.  Do you know where is wrong?

**Comment by Vinohith** [comment]
Not very sure. I had worked with this repository quiet a while back and I had made only the mentioned change for the algorithm to work properly and produce good results.
