### ISSUE TITLE
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation

### ISSUE THREAD

**Issue by kaixinbear** [lzccccc/SMOKE#17]
Hi ,I am interested in your work.
When I run `python tools/plain_train_net.py --config-file "configs/smoke_gn_vector.yaml"`
there is a bug:
```
Traceback (most recent call last):
  File "tools/plain_train_net.py", line 100, in <module>
    args=(args,),
  File "/home/kaixin/jupyter_projects/Project/SMOKE/smoke/engine/launch.py", line 56, in launch
    main_func(*args)
  File "tools/plain_train_net.py", line 88, in main
    train(cfg, model, device, distributed)
  File "tools/plain_train_net.py", line 53, in train
    arguments
  File "/home/kaixin/jupyter_projects/Project/SMOKE/smoke/engine/trainer.py", line 76, in do_train
    losses.backward()
  File "/home/kaixin/anaconda3/lib/python3.6/site-packages/torch/tensor.py", line 102, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/kaixin/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation
```
Can you do me a favor?I use Pytorch1.0.0

**Comment by Gaozihui** [comment]
Hi~
I am having the same problem as you. And I have set all the INPLACE=FALSE in the loss calculation but it didn't work.
Have you worked it out? I would appreciate that if you can share your experience with me. Thanks in advance!

I use Pytorch 1.2.0
