### ISSUE TITLE
ERROR: Couldn't read: 001062.txt of ground truth. Please write me an email!

### ISSUE THREAD

**Issue by r850727** [lzccccc/SMOKE#4]
May you give me the ground truth file?
Thank you.

**Comment by tdtce** [comment]
@r850727 Hello! What command did you use when get this error?
Repo has file kitti_eval.py. Absolute path: "./smoke/data/datasets/evaluation/kitti/kitti_eval.py".

Which directory do you run your command from? Try running this command from the root of package SMOKE.

**Comment by lzccccc** [comment]
Hi,

You need to put offline kitti eval code under the folder "/smoke/data/datasets/evaluation/kitti/kitti_eval"
if you are using the train/val split. It will compile it automatically and evaluate the performance.
The eval code can be found here: 
https://github.com/prclibo/kitti_eval (for 11 recall points)
https://github.com/lzccccc/kitti_eval_offline (for 40 recall points)

However, if you are using the trainval (namely the whole training set), there is no need to evaluate it offline. You need to log in to the kitti webset and submit your result.

**Comment by r850727** [comment]
Thanks for your response let me solve the problem.
How can I show visible results with your code? 
just like your video.

**Comment by lzccccc** [comment]
The visualization code is not included in this repo.
A similar one can be found here: https://github.com/lzccccc/3d-bounding-box-estimation-for-autonomous-driving/blob/master/utils/visualization3Dbox.py

**Comment by lfydegithub** [comment]
have the same issue.
```pyhton
[2020-04-24 14:35:57,169] smoke.data.datasets.evaluation.kitti.kitti_eval INFO: Evaluate on KITTI dataset
Traceback (most recent call last):
  File "tools/plain_train_net.py", line 100, in <module>
    args=(args,),
  File "/home/holo/workspace/pyspace/SMOKE/smoke/engine/launch.py", line 56, in launch
    main_func(*args)
  File "tools/plain_train_net.py", line 79, in main
    return run_test(cfg, model)
  File "/home/holo/workspace/pyspace/SMOKE/smoke/engine/test_net.py", line 26, in run_test
    output_folder=output_folder,
  File "/home/holo/workspace/pyspace/SMOKE/smoke/engine/inference.py", line 74, in inference
    output_folder=output_folder, )
  File "/home/holo/workspace/pyspace/SMOKE/smoke/data/datasets/evaluation/__init__.py", line 26, in evaluate
    return kitti_evaluation(**args)
  File "/home/holo/workspace/pyspace/SMOKE/smoke/data/datasets/evaluation/kitti/kitti_eval.py", line 28, in kitti_evaluation
    logger=logger
  File "/home/holo/workspace/pyspace/SMOKE/smoke/data/datasets/evaluation/kitti/kitti_eval.py", line 48, in do_kitti_detection_evaluation
    os.chdir('../smoke/data/datasets/evaluation/kitti/kitti_eval')
FileNotFoundError: [Errno 2] No such file or directory: '../smoke/data/datasets/evaluation/kitti/kitti_eval'
```

**Comment by lzccccc** [comment]
@lfydegithub 

Please follow the steps l mentioned here.

> Hi,
> 
> You need to put offline kitti eval code under the folder "/smoke/data/datasets/evaluation/kitti/kitti_eval"
> if you are using the train/val split. It will compile it automatically and evaluate the performance.
> The eval code can be found here:
> https://github.com/prclibo/kitti_eval (for 11 recall points)
> https://github.com/lzccccc/kitti_eval_offline (for 40 recall points)
> 
> However, if you are using the trainval (namely the whole training set), there is no need to evaluate it offline. You need to log in to the kitti webset and submit your result.

**Comment by lfydegithub** [comment]
> @lfydegithub
> 
> Please follow the steps l mentioned here.
> 
> > Hi,
> > You need to put offline kitti eval code under the folder "/smoke/data/datasets/evaluation/kitti/kitti_eval"
> > if you are using the train/val split. It will compile it automatically and evaluate the performance.
> > The eval code can be found here:
> > https://github.com/prclibo/kitti_eval (for 11 recall points)
> > https://github.com/lzccccc/kitti_eval_offline (for 40 recall points)
> > However, if you are using the trainval (namely the whole training set), there is no need to evaluate it offline. You need to log in to the kitti webset and submit your result.

thx !~ 
but ```../smoke/data/datasets/evaluation/kitti/kitti_eval``` should be ```./smoke/data/datasets/evaluation/kitti/kitti_eval```

**Comment by XiwuChen** [comment]
> Hi,
> 
> You need to put offline kitti eval code under the folder "/smoke/data/datasets/evaluation/kitti/kitti_eval"
> if you are using the train/val split. It will compile it automatically and evaluate the performance.
> The eval code can be found here:
> https://github.com/prclibo/kitti_eval (for 11 recall points)
> https://github.com/lzccccc/kitti_eval_offline (for 40 recall points)
> 
> However, if you are using the trainval (namely the whole training set), there is no need to evaluate it offline. You need to log in to the kitti webset and submit your result.

Can you upload these files to this repository and make it easier to use. Thk.
