### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/kitti/testing/ImageSets/test.txt'

### ISSUE THREAD

**Issue by Adonis-galaxy** [lzccccc/SMOKE#55]
How to deal with:
It seems like a root path bug.

Traceback (most recent call last):
  File "tools/plain_train_net.py", line 100, in <module>
    args=(args,),
  File "/sdc/zzy/code/smoke/smoke/engine/launch.py", line 56, in launch
    main_func(*args)
  File "tools/plain_train_net.py", line 79, in main
    return run_test(cfg, model)
  File "/sdc/zzy/code/smoke/smoke/engine/test_net.py", line 19, in run_test
    data_loaders_val = build_test_loader(cfg)
  File "/sdc/zzy/code/smoke/smoke/data/build.py", line 134, in build_test_loader
    datasets = build_dataset(cfg, transforms, DatasetCatalog, is_train)
  File "/sdc/zzy/code/smoke/smoke/data/build.py", line 45, in build_dataset
    dataset = factory(**args)
  File "/sdc/zzy/code/smoke/smoke/data/datasets/kitti.py", line 54, in __init__
    for line in open(imageset_txt, "r"):
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/kitti/testing/ImageSets/test.txt'

**Comment by Chad-Sun** [comment]
Maybe you should create a TXT file, similar to VOC, containing the name of the picture to be tested
Like:
000000
000001
000002

**Comment by ZNHzlq** [comment]
@Adonis-galaxy Hello! I have meet the same problem, did you solve it?
