### ISSUE TITLE
TypeError: zip argument #1 must support iteration

### ISSUE THREAD

**Issue by zfyong** [lzccccc/SMOKE#6]
I met this problem, but really dont konw how to solve. some one can help me?
```
Traceback (most recent call last):
  File "tools/plain_train_net.py", line 102, in <module>
    args=(args,),
  File "/home/zhifanyong/deep_learning/SMOKE/smoke/engine/launch.py", line 53, in launch
    daemon=False,
  File "/home/zhifanyong/venv/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 171, in spawn
    while not spawn_context.join():
  File "/home/zhifanyong/venv/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/zhifanyong/venv/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/home/zhifanyong/deep_learning/SMOKE/smoke/engine/launch.py", line 88, in _distributed_worker
    main_func(*args)
  File "/home/zhifanyong/deep_learning/SMOKE/tools/plain_train_net.py", line 90, in main
    train(cfg, model, device, distributed)
  File "/home/zhifanyong/deep_learning/SMOKE/tools/plain_train_net.py", line 53, in train
    arguments
  File "/home/zhifanyong/deep_learning/SMOKE/smoke/engine/trainer.py", line 58, in do_train
    for data, iteration in zip(data_loader, range(start_iter, max_iter)):
TypeError: zip argument #1 must support iteration
```

**Comment by lzccccc** [comment]
Hi,

It seems like a problem with the data_loader.
Did you follow Requirements in the README file?

**Comment by Twizwei** [comment]
Hi there, I met the same issue. I did follow the README file and actually ran eval_only successfully. The issue came out when I tried to train the model.

**Comment by Twizwei** [comment]
I solved this issue by switching my Python to 3.7 and Pytorch 1.3 as Requirements. Although I'm not fully clear why this happened, this might be due to some changes between different PyTorch versions that Detectron can't be perfectly compatible. I also met a similar issue when I ran maskrcnn-benchmark.

**Comment by ktertikas** [comment]
I was also encountering this issue. Just FYI once I removed the logger from the dataset, everything seemed to work fine.

**Comment by FANzhaoxin666** [comment]
i sovle the problem by setting the num_works=0

**Comment by ailovejinx** [comment]
> i sovle the problem by setting the num_works=0

I don't know why but it works. Thanks bro! 😀
