### ISSUE TITLE
ImportError：cannot import name ' download_ url_ to file' from 'torch .hub' ( /home/dyj/ anaconda3/envs/SMOKE/lib/python3.7/site- packages/torch hub. py)

### ISSUE THREAD

**Issue by Lan2Kailee** [lzccccc/SMOKE#62]
Traceback (most recent call last):
File "plain train net.py", line 9，in <module>
from smoke .utils. check point import Detectr onCheckpointer
File " /home/dyj/SMOKE/ smoke/utils/check point.py", line 8, in <module>
from smoke · utils .model_ Z0O import cache url
File ' /home/dyj/ SMOKE/ smoke/utils/model_ z00 .py", line 5, in <module>
from torch. hub import download_ url_ to file
ImportError: cannot import name ' download_ url_ to file' from 'torch .hub' ( /home/dyj/ anaconda3/envs/SMOKE/lib/python3.7/site- packages/torch hub. py)

**Comment by zzy0731** [comment]
hi i meet a same problem ,how do you solve it

**Comment by zzy0731** [comment]
hey think i found a solution ,if you need ,you can ask me
